### ISSUE TITLE
Installation Failed

### ISSUE THREAD

**Issue by gqtn** [lezhnev74/HLS-monitor#1]
Hello.

I've been trying to install this through composer, but I'm having some errors that are preventing it from installing correctly:

> 
> Using version ^1.0 for lezhnev74/hls-monitor
> ./composer.json has been created
> Running composer update lezhnev74/hls-monitor
> Loading composer repositories with package information
> Updating dependencies
> Your requirements could not be resolved to an installable set of packages.
> 
>   Problem 1
>     - lezhnev74/hls-monitor[v1.0.0, ..., 1.0.9] require webmozart/console ~1.0@beta -> found webmozart/console[dev-master, 1.0.0-beta, ..., 1.0.x-dev (alias of dev-master)] but it does not match your minimum-stability.
>     - Root composer.json requires lezhnev74/hls-monitor ^1.0 -> satisfiable by lezhnev74/hls-monitor[v1.0.0, ..., 1.0.9].
> 
> Installation failed, deleting ./composer.json.

My system:
> Linux debian 5.10.0-11-amd64 #1 SMP Debian 5.10.92-1 (2022-01-18) x86_64 GNU/Linux
> PHP 7.4.25 (cli) (built: Oct 23 2021 21:53:50) ( NTS )

Could you help me?

Thank you,
Gabriel Quintana.

**Comment by lezhnev74** [comment]
Hey @quintanaplaca , I forgot this package existed. Ok, I did some updates and maybe now it'll work as expected.

Try `composer update` again, the new code is tagged `1.0.10`

**Comment by lezhnev74** [comment]
Oh, I actually realized what the problem is. The package is unstable and you have to put this line to your composer.json file in order to allow unstable packages:
```
"minimum-stability": "beta"
```

**Comment by gqtn** [comment]
Hello.

I thank you for your quick response.

I apologize as I don't have full mastery of composer, and this is being my first iteration with it, and I would really like to test your solution.

Well, I've installed the latest version of Composer, and I've already migrated it to `/usr/bin` to access in any environment.

> Composer version 2.2.6 2022-02-04 17:00:38

And I created a folder, and inside it I already have the files:

> composer.phar
> composer-setup.php
> composer.json (created manually)
> 

But even so, when I try to require, or do the update, I get the following message:

>   problem 1
>     - lezhnev74/hls-monitor[v1.0.0, ..., 1.0.10] require webmozart/console ~1.0@beta -> found webmozart/console[dev-master, 1.0.0-beta, ..., 1.0. x-dev (alias of dev-master)] but it does not match your minimum-stability.
>     - Root composer.json requires lezhnev74/hls-monitor ^1.0 -> satisfiable by lezhnev74/hls-monitor[v1.0.0, ..., 1.0.10].

Should I add that line in the `"minimum-stability" file: "beta"` inside my `composer.json` file?

My file looks like this:

```
{
    "require": {
        "lezhnev74/hls-monitor": "^1.0"
    }
}
```

I'm not sure if it's necessary to do a git clone, and run the processes inside the folder created after that.

And, well, I appreciate your patience and attention with me on this. I understand that I should study more, and I would appreciate your support.

![composer](https://user-images.githubusercontent.com/74671431/154312118-3979f472-8f4e-422e-8b27-d25c5593bc97.png)

Thank you,
Gabriel Quintana.

**Comment by lezhnev74** [comment]
Ok, try this:
1. have a file `composer.json` with this content:
```
{
    "require": {
        "lezhnev74/hls-monitor": "^1.0"
    },
    "minimum-stability": "beta"
}
```
2. in the same folder run `composer update`
3. then run `vendor/bin/hls-monitor playlists --log log.txt --concurrency=10 https://bitdash-a.akamaihd.net/content/sintel/hls/playlist.m3u8`

**Comment by gqtn** [comment]
Hello.

Yes, I thought about this. So, thank you a lot! It is working well now.

> #---------------------------------------------------
> Executed on node: 177.125.175.2
> Date of execution: 17.02.2022, 08:54 -03
> #---------------------------------------------------
> 
> Concurrency level:50
> Log:log.txt
> Playlists fetching is over in 0.04s
> Streams fetching is over in 0s
> Chunks fetching is over in 0s

I will update the script now.

Have a great day, and thank you again!
Gabriel Quintana.
